import { getAllPosts } from "@/pages/api/wordpress";
import styles from "@/styles/blog/blog.module.scss";
import Container from "@/components/content/container";
import Text from "@/components/content/text";
import Button from "@/components/content/button";
import { Kanit, Nunito_Sans } from 'next/font/google'
import Head from 'next/head'
import Link from "next/link";


const title = Kanit({ subsets: ['latin'], weight: "700" })
const text = Nunito_Sans({ subsets: ['latin'], weight: "400" })

export default function Blog({ data }) {

    return (
        <>
            <Head>
                <title>El blog de Kaoos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.svg" />
                <script src="echarts.js"></script>
            </Head>
            <Container className={`${styles.root} ${text.className}`} fullscreen>
                <div>
                    <Text xxxl className={`${title.className} ${styles.title} `}>TRÁFICO CONSTANTE Y CUALIFICADO</Text>
                    <Text xxl className={`${title.className} ${styles.title} `}>DESCUBRE DE QUE TRATA EL SEO</Text>

                    <div className={styles.content}>
                        <div className={styles.list}>
                            {
                                data.edges.map((blog) => {
                                    return (
                                        <Link href={`/blog/${blog.node.slug}`}>
                                            <img alt={blog.node.featuredImage.node.altText} src={blog.node.featuredImage.node.sourceUrl} />
                                        </Link>
                                    )
                                })
                            }
                        </div>
                        <div className={styles.sidebar}>
                            <Text xl>¿Abrumado con demasiada información?</Text>
                            <Text>Comienza a posicionar tu web y obtener tráfico real desde ya con nuestra ayuda.<br></br> Kaoos es una agencia especializada en diseño web y posicionamiento.</Text>
                            <div className={styles.actions}>
                                <Button>Ver Diseños</Button>
                                <Button highlight={true}>Ver Proyectos</Button>
                            </div>
                        </div>
                    </div>
                </div>

            </Container>
        </>
    )
}

export const getStaticProps = async () => {
    const data = await getAllPosts("blog");
    return {
        props: {
            data
        },
    };
}