import Head from 'next/head'
import { Nunito_Sans } from 'next/font/google'
import styles from '../styles/home.module.scss'
import Header from '../components/header'
import Hero from '../components/hero'
import Aos from '../components/aos'
import SeoCharts from '../components/seo-charts'

const arimo = Nunito_Sans({ subsets: ['latin'], weight: "400" })


export default function Home() {

    const data = [
        { name: '01/2023', visitas: 250000 },
        { name: '02/2023', visitas: 275000 },
        { name: '03/2023', visitas: 128452 },
        { name: '04/2023', visitas: 174000 },
    ]

    /*
    const testRef = useRef(null);
    const [renderChart, setRenderChart] = useState(false);

    useEffect(() => {
        const observer = new IntersectionObserver((entries) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    setRenderChart(true);
                }
            })
        }, { threshold: 0.9 })

        observer.observe(testRef.current)
    }, [])

    */


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="echarts.js"></script>
            </Head>

            {/* MUST SEE FOR LATER
            
                PROYECTO WEB
                https://mkosir.github.io/react-parallax-tilt/?path=/story/react-parallax-tilt--parallax-effect-glare-scale <-- para las imgs
                https://www.lightgalleryjs.com/demos/thumbnails/
                https://merri.github.io/react-tabbordion <-- FAQ
                https://www.npmjs.com/package/next-seo
                https://www.npmjs.com/package/next-sitemap
                https://www.npmjs.com/package/nextjs-google-analytics
                https://github.com/rcaferati/react-awesome-slider <-- full page slider ¿(Casos de exito)?

                MISCELANEA
                https://github.com/malerba118/react-particle-image <-- Particulas en una img, tengo que probarlo
                https://github.com/gilbarbara/react-joyride <-- Plataforma servicios
                https://react-icons.github.io/react-icons <-- Iconos
                https://sweetalert2.github.io/ <-- Alertas muy bonitas
                https://github.com/sgwilym/windups <-- para orientar al usuario, mola.
                https://github.com/drgx/react-thanos-snap <-- efectos snap thanos mola
                
                TIENDA
                https://github.com/amaroteam/react-credit-cards <-- Proyecto tienda
                https://react-rating.onrender.com/ <-- Rating estrellas
                https://sonner.emilkowal.ski/ <-- notificaciones fácil.
                
                BLOG INSPIRATION
                sendcloud webpage

            */}
            <Header />
            <Aos />
            <main className={`${styles.main} ${arimo.className}`}>
                <Hero />
                <SeoCharts />
                <section style={{ minHeight: "500px", width: "100%" }}></section>
                <section style={{ minHeight: "500px", width: "100%" }}></section>
            </main>

        </>
    )
}
