import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import H1 from '@/components/h1'
import H2 from '@/components/h2'
import Button from '@/components/button'
import Text from '@/components/text'
import Highlight from '@/components/highlight'
import Section from '@/components/section'
import Chart from '@/components/chart-views'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

    const data = [
        { name: '01/2023', visitas: 250000 },
        { name: '02/2023', visitas: 275000 },
        { name: '03/2023', visitas: 128452 },
        { name: '04/2023', visitas: 174000 },
    ]

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="echarts.js"></script>
            </Head>

            <main className={styles.main}>
                <Section large={true}>
                    <Chart title={"DeBocado"} data={data} />
                    <H1>Prueba H1</H1>
                    <H2>Prueba H1</H2>
                    <Button displaySvg={true}>Ver proyectos</Button>
                    <Text>Texto de ejemplo</Text>
                    <Text>Texto de ejemplo <Highlight>con highlight</Highlight></Text>
                </Section>
            </main>
        </>
    )
}
