import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import H1 from '@/components/h1'
import H2 from '@/components/h2'
import Text from '@/components/text'
import Highlight from '@/components/highlight'
import Section from '@/components/section'
import Chart from '@/components/chart-views'
import Header from '@/components/header'
import Hero from '@/components/hero'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

    const data = [
        { name: '01/2023', visitas: 250000 },
        { name: '02/2023', visitas: 275000 },
        { name: '03/2023', visitas: 128452 },
        { name: '04/2023', visitas: 174000 },
    ]

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="echarts.js"></script>
            </Head>

            {/* MUST SEE FOR LATER
            
                PROYECTO WEB
                https://mkosir.github.io/react-parallax-tilt/?path=/story/react-parallax-tilt--parallax-effect-glare-scale <-- para las imgs
                https://www.lightgalleryjs.com/demos/thumbnails/
                https://github.com/rommguy/react-custom-scroll
                https://merri.github.io/react-tabbordion <-- FAQ
                https://www.npmjs.com/package/next-seo
                https://www.npmjs.com/package/next-sitemap
                https://www.npmjs.com/package/nextjs-google-analytics
                https://github.com/rcaferati/react-awesome-slider <-- full page slider ¿(Casos de exito)?

                MISCELANEA
                https://github.com/malerba118/react-particle-image <-- Particulas en una img, tengo que probarlo
                https://github.com/gilbarbara/react-joyride <-- Plataforma servicios
                https://react-icons.github.io/react-icons <-- Iconos
                https://sweetalert2.github.io/ <-- Alertas muy bonitas

                TIENDA
                https://github.com/amaroteam/react-credit-cards <-- Proyecto tienda
                https://react-rating.onrender.com/ <-- Rating estrellas
                
                BLOG INSPIRATION
                sendcloud webpage
            */}
            <Header />
            <main className={styles.main}>
                <Hero />
                
            </main>
        </>
    )
}
